apiVersion: v1
kind: ConfigMap
metadata:
  name: config-cybersec
  namespace: ai-agents
  labels:
    team: development
    agent: cybersec
data:
  agent-cybersec.yaml: |
    - id: cybersec
      name: "Jade"
      model: "ollama/qwen3-next:80b-cloud"
      chatModel: "ollama/qwen3-next:80b-cloud"
