apiVersion: v1
kind: ConfigMap
metadata:
  name: config-ux
  namespace: ai-agents
  labels:
    team: development
    agent: ux
data:
  agent-ux.yaml: |
    - id: ux
      name: "Luna"
      model: "ollama/ministral-3:14b-cloud"
      chatModel: "ollama/ministral-3:14b-cloud"
