apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - nvidia-runtimeclass.yaml
  - nvidia-device-plugin.yaml

patches:
  - path: ollama-gpu-patch.yaml
    target:
      kind: Pod
      name: ollama
