apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
spec:
  template:
    spec:
      runtimeClassName: nvidia
      containers:
        - name: ollama
          resources:
            requests:
              cpu: "1"
              memory: 2Gi
              nvidia.com/gpu: 1
            limits:
              cpu: "4"
              memory: 16Gi
              nvidia.com/gpu: 1
