apiVersion: v1
kind: ConfigMap
metadata:
  name: config-dba
  namespace: ai-agents
  labels:
    team: development
    agent: dba
data:
  agent-dba.yaml: |
    - id: dba
      name: "Dante"
      model: "ollama/ministral-3:14b-cloud"
      chatModel: "ollama/ministral-3:14b-cloud"
