apiVersion: v1
kind: ConfigMap
metadata:
  name: config-developer
  namespace: ai-agents
  labels:
    team: development
    agent: developer
data:
  agent-developer.yaml: |
    - id: developer
      name: "Leo"
      model: "ollama/ministral-3:14b-cloud"
      chatModel: "ollama/ministral-3:14b-cloud"
