apiVersion: v1
kind: ConfigMap
metadata:
  name: config-architect
  namespace: ai-agents
  labels:
    team: development
    agent: architect
data:
  agent-architect.yaml: |
    - id: architect
      name: "Vera"
      model: "ollama/ministral-3:14b-cloud"
      chatModel: "ollama/ministral-3:14b-cloud"
