apiVersion: v1
kind: ConfigMap
metadata:
  name: config-devops
  namespace: ai-agents
  labels:
    team: development
    agent: devops
data:
  agent-devops.yaml: |
    - id: devops
      name: "Sérgio"
      model: "ollama/ministral-3:14b-cloud"
      chatModel: "ollama/ministral-3:14b-cloud"
