apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-data
  labels:
    app: ollama
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 50Gi
